[cpu]
name = "11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz"
curve = [171.2,0.0354,36.89,-10.13]

[[process]]
name = "bare_process"
up = "./test_cardamon/target/release/test_cardamon"
down = "kill {pid}"
redirect.to = "file"
process.type = "baremetal"

[[process]]
name = "docker_process"
up = "docker compose -f ./test_cardamon/compose.yaml up -d"
down = "docker compose -f ./test_cardamon/compose.yaml down"
redirect.to = "file"
process.type = "docker"
process.containers = ["test_cardamon_container"]
startup_grace = "8000ms"

[[scenario]]
name = "bare_scenario"
desc = "bare"
command = "curl localhost:3000"
iterations = 5
processes = ["bare_process"]

[[scenario]]
name = "docker_scenario"
desc = "docekr"
command = "curl localhost:3000"
iterations = 5
processes = ["docker_process"]

[[observation]]
name = "bare"
scenarios = ["bare_scenario"]


[[observation]]
name = "docker"
scenarios = ["docker_scenario"]
